// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqfdqivdyczqxnroncqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxZmRxaXZkeWN6cXhucm9uY3F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MDQxMTUsImV4cCI6MjA2NTM4MDExNX0.GLSUgjwmjBj953QuN_oiBPy3ea4-z5ZE_r2TEgSiO8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);